services:
    postgres:
        container_name: aegis-id-db
        image: postgres:17.5-alpine
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            PG_DATA: /data/postgres
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - postgres:/data/postgres
        ports:
            - "5432:5432"
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
            interval: 10s
            timeout: 5s
            retries: 5

    app:
        container_name: aegis-id-app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
            - "8081:8081"
        environment:
            APP_NAME: ${APP_NAME}
            SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}
            DB_URL: postgres
            DB_PORT: 5432
            DB_NAME: ${DB_NAME}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            JWT_PRIVATE_KEY_LOCATION: ${JWT_PRIVATE_KEY_LOCATION:-file:/run/secrets/jwt_private_key}
            JWT_PUBLIC_KEY_LOCATION: ${JWT_PUBLIC_KEY_LOCATION:-file:/run/secrets/jwt_public_key}
            JWT_ACCESS_TOKEN_EXPIRATION: ${JWT_ACCESS_TOKEN_EXPIRATION}
            JWT_REFRESH_TOKEN_EXPIRATION: ${JWT_REFRESH_TOKEN_EXPIRATION}
            JWT_INCLUDE_ROLES_CLAIM: ${JWT_INCLUDE_ROLES_CLAIM:-false}
            MANAGEMENT_PORT: ${MANAGEMENT_PORT:-8081}
        secrets:
            - source: jwt_private_key
              target: jwt_private_key
            - source: jwt_public_key
              target: jwt_public_key
        depends_on:
            postgres:
                condition: service_healthy
        restart: unless-stopped

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-root}
        ports:
            - "5050:80"
        depends_on:
            - postgres

secrets:
    jwt_private_key:
        file: ${JWT_PRIVATE_KEY_FILE:-./secrets/jwt/private_key.pem}
    jwt_public_key:
        file: ${JWT_PUBLIC_KEY_FILE:-./secrets/jwt/public_key.pem}

volumes:
    postgres:
